### ISSUE TITLE
Headings should not be rendered isolated at the bottom of a page.

### ISSUE THREAD

**Issue by yashha** [danburzo/percollate#110]
To reproduce:
[Link](https://api.readtheweb.de/load.pdf?&url=https%3A%2F%2Fgithub.com%2FSaraVieira%2Fstarter-book&pagesperside=1&css=html%20%7B%20font-size%3A%2012pt%20%7D%40page%20%7B%20size%3A%20a5%20portrait%20%7D)

I searched for a solution before, but now I this very cool snippet!
https://stackoverflow.com/questions/9238868/how-do-i-avoid-a-page-break-immediately-after-a-heading/53742871#53742871

```css
h1, h2 {
    page-break-inside: avoid;
}
h1::after, h2::after  {
    content: "";
    display: block;
    height: 100px;
    margin-bottom: -100px;
}
```

We should just add the other hX tags.

Here can it be tested [with the css](https://api.readtheweb.de/load.pdf?&url=https%3A%2F%2Fgithub.com%2FSaraVieira%2Fstarter-book&pagesperside=1&css=html%20%7B%20font-size%3A%2012pt%20%7D%40page%20%7B%20size%3A%20a5%20portrait%20%7Dh1%2Ch2%20%7B%0A%20%20%20%20page-break-inside%3A%20avoid%3B%0A%7D%0Ah1%3A%3Aafter%2C%20h2%3A%3Aafter%20%20%7B%0A%20%20%20%20content%3A%20%22%22%3B%0A%20%20%20%20display%3A%20block%3B%0A%20%20%20%20height%3A%20100px%3B%0A%20%20%20%20margin-bottom%3A%20-100px%3B%0A%7D), [here without](https://api.readtheweb.de/load.pdf?&url=https%3A%2F%2Fgithub.com%2FSaraVieira%2Fstarter-book&pagesperside=1&css=html%20%7B%20font-size%3A%2012pt%20%7D%40page%20%7B%20size%3A%20a5%20portrait%20%7D)
