### ISSUE TITLE
Some pages result in smaller font size

### ISSUE THREAD

**Issue by danburzo** [danburzo/percollate#85]
On some pages, e.g.

```bash
percollate pdf pdf https://de.wikipedia.org/wiki/JavaScript
```

The font size in the resulting PDF is much smaller than usual, although the page size remains the same.

**Comment by danburzo** [comment]
It can be fixed with:

```css
html, body {
  width: 100%;
  overflow: hidden;
}
```

But it causes wide tables to get clipped and I'm not sure whether we should do this by default.
